/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'huzhifeng' at '2/17/16 10:34 AM' with Gradle 2.11
 *
 * @author huzhifeng, @date 2/17/16 10:34 AM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
