/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'huzhifeng' at '2/17/16 10:34 AM' with Gradle 2.11
 *
 * @author huzhifeng, @date 2/17/16 10:34 AM
 */
import push.android.AndroidBroadcast;

public class Library {
    public boolean someLibraryMethod() {
        String appkey = "test";
        String appMasterSecret = "demo";
        try {
        AndroidBroadcast broadcast = new AndroidBroadcast(appkey,appMasterSecret);
        } catch (Exception e) {
            System.out.println(e);
        }

        return true;
    }
}
